def draw_weight_settings(self):
    layout = self.layout
    row = layout.row()
    row.prop(self, 'mode')
    row = layout.row()
    row.prop(self, 'shape')
    row = layout.row()
    row.prop(self, 'offset')
    row = layout.row()
    row.prop(self, 'rotate')
    row = layout.row()
    row.prop(self, 'scale')
    row = layout.row()
    row.prop(self, 'origin')
    row = layout.row()
    row.prop(self, 'taper')
    row.enabled = self.shape in ('CYLINDER', 'CAPSULE', 'CUBE')
    row = layout.row()
    row.prop(self, 'blend')
    row = layout.row()
    row.prop(self, 'weight')
    row = layout.row()
    row.prop(self, 'invert')
    row.prop(self, 'remove')
    row.prop(self, 'show')
